/**
 * @file gltf_animation_test.cpp
 * @brief Checks glTF loading and skeletal animation against a known asset.
 *
 * tests/assets/skinned_bar.gltf is a two-joint bar generated by
 * tools/make_test_gltf.py, chosen so its correct poses can be worked out by
 * hand: the lower joint never moves, and the upper joint rotates 90 degrees
 * about +Z over one second.
 *
 * Uploading meshes needs a GL context, so the test opens a hidden window
 * rather than running purely on the CPU.
 */

#include "nle/model/model_gltf.h"
#include "nle/model/gltf_instance_3d.h"

#include <GL/glew.h>
#include <GLFW/glfw3.h>

#include <glm/gtc/matrix_transform.hpp>

#include <cmath>
#include <cstdlib>
#include <iostream>
#include <string>

namespace
{

int g_failures = 0;
int g_checks = 0;

void check(bool condition, const std::string& what)
{
    ++g_checks;
    if(condition)
    {
        std::cout << "  ok   " << what << "\n";
    }
    else
    {
        ++g_failures;
        std::cout << "  FAIL " << what << "\n";
    }
}

void check_near(float actual, float expected, const std::string& what, float tolerance = 1e-4f)
{
    const bool ok = std::fabs(actual - expected) <= tolerance;
    ++g_checks;
    if(ok)
    {
        std::cout << "  ok   " << what << " (" << actual << ")\n";
    }
    else
    {
        ++g_failures;
        std::cout << "  FAIL " << what << ": expected " << expected << ", got " << actual << "\n";
    }
}

void check_vec3_near(const glm::vec3& actual, const glm::vec3& expected, const std::string& what,
                     float tolerance = 1e-4f)
{
    const bool ok = std::fabs(actual.x - expected.x) <= tolerance &&
                    std::fabs(actual.y - expected.y) <= tolerance &&
                    std::fabs(actual.z - expected.z) <= tolerance;
    ++g_checks;
    if(ok)
    {
        std::cout << "  ok   " << what << " (" << actual.x << ", " << actual.y << ", " << actual.z << ")\n";
    }
    else
    {
        ++g_failures;
        std::cout << "  FAIL " << what << ": expected (" << expected.x << ", " << expected.y << ", "
                  << expected.z << "), got (" << actual.x << ", " << actual.y << ", " << actual.z << ")\n";
    }
}

bool is_identity(const glm::mat4& matrix, float tolerance = 1e-4f)
{
    for(int column = 0; column < 4; ++column)
    {
        for(int row = 0; row < 4; ++row)
        {
            const float expected = column == row ? 1.0f : 0.0f;
            if(std::fabs(matrix[column][row] - expected) > tolerance)
            {
                return false;
            }
        }
    }
    return true;
}

void test_model(const std::string& path)
{
    std::cout << "\n== " << path << " ==\n";

    auto model = nle::make_ref<nle::model_gltf>(path);

    check(model->primitives().size() == 1, "one primitive");
    check(model->skinned(), "model reports a skin");

    const auto& skeleton = model->skeleton();
    check(skeleton->nodes().size() == 3, "three nodes");
    check(skeleton->roots().size() == 2, "two root nodes");
    check(skeleton->skins().size() == 1, "one skin");

    if(skeleton->skins().empty())
    {
        return;
    }

    check(skeleton->skins()[0].joints.size() == 2, "skin has two joints");
    check(skeleton->skins()[0].inverse_bind_matrices.size() == 2, "two inverse bind matrices");

    const auto names = model->animation_names();
    check(names.size() == 1 && names[0] == "bend", "one clip named 'bend'");

    if(model->animations().empty())
    {
        return;
    }

    check_near(model->animations()[0]->duration(), 1.0f, "clip duration is one second");

    // Geometry: normals are absent from the file and must have been generated,
    // and the skin weights must be present and normalised.
    const auto& mesh = model->primitives()[0].mesh;
    check(mesh->vertices().size() == 8, "eight vertices");
    check(mesh->indices().size() == 36, "thirty-six indices");
    check(model->primitives()[0].skin == 0, "primitive is bound to skin 0");

    bool normals_generated = true;
    bool weights_normalised = true;
    for(const auto& v : mesh->vertices())
    {
        if(glm::length(v.normal) < 0.5f)
        {
            normals_generated = false;
        }

        const float total = v.weights.x + v.weights.y + v.weights.z + v.weights.w;
        if(std::fabs(total - 1.0f) > 1e-4f)
        {
            weights_normalised = false;
        }
    }
    check(normals_generated, "normals were generated for a file without them");
    check(weights_normalised, "skin weights sum to one");

    // The bottom ring is weighted to joint 0, the top ring to joint 1.
    check(mesh->vertices()[0].joints.x == 0.0f, "bottom vertex uses joint 0");
    check(mesh->vertices()[4].joints.x == 1.0f, "top vertex uses joint 1");

    // ---- animation ------------------------------------------------------
    auto instance = model->create_gltf_instance();
    auto animator = instance->animator();

    check(animator != nullptr, "instance has an animator");
    check(animator->play("bend"), "clip 'bend' can be played");
    check(!animator->play("does_not_exist"), "an unknown clip is rejected");

    // At t=0 the pose is the bind pose, so every joint matrix is the identity.
    animator->seek(0.0f);
    const auto& palette_start = animator->joint_matrices(0);
    check(palette_start.size() == 2, "palette has one matrix per joint");

    if(palette_start.size() != 2)
    {
        return;
    }

    check(is_identity(palette_start[0]), "t=0: joint 0 matrix is the identity");
    check(is_identity(palette_start[1]), "t=0: joint 1 matrix is the identity");

    // On a looping clip the end of the clip is the start of the next lap, so
    // seeking to the duration lands back on the first frame.
    animator->seek(1.0f);
    check(is_identity(animator->joint_matrices(0)[1]), "looping: seeking to the duration wraps to t=0");

    // At t=1 joint 1 has rotated 90 degrees about +Z around its own origin at
    // y=1. A top vertex at (0.25, 2, 0.25) therefore lands at (-1, 1.25, 0.25).
    // The clip has to be non-looping for the final frame to be reachable.
    animator->play("bend", false);
    animator->seek(1.0f);
    const auto& palette_end = animator->joint_matrices(0);

    check(is_identity(palette_end[0]), "t=1: joint 0 has still not moved");

    const glm::vec3 top_vertex(0.25f, 2.0f, 0.25f);
    const glm::vec3 skinned = glm::vec3(palette_end[1] * glm::vec4(top_vertex, 1.0f));
    check_vec3_near(skinned, glm::vec3(-1.0f, 1.25f, 0.25f), "t=1: top of the bar swung to -X");

    // Halfway through, the joint is at 45 degrees: the tip should be part of
    // the way round, and strictly between the two extremes.
    animator->play("bend", true);
    animator->seek(0.5f);
    const glm::vec3 half = glm::vec3(animator->joint_matrices(0)[1] * glm::vec4(top_vertex, 1.0f));
    check(half.x < -0.1f && half.x > -1.0f, "t=0.5: tip is between the bind pose and the end pose");
    check(half.y > 1.25f && half.y < 2.0f, "t=0.5: tip has dropped but not fully");

    // Looping should wrap back onto the start of the clip.
    animator->play("bend", true);
    animator->update(1.25f);
    check_near(animator->time(), 0.25f, "looping wraps past the end of the clip");

    // A non-looping clip stops on its last frame.
    animator->play("bend", false);
    animator->update(5.0f);
    check_near(animator->time(), 1.0f, "a non-looping clip clamps to its duration");
    check(!animator->playing(), "a non-looping clip stops when it ends");

    // stop() returns to the bind pose.
    animator->stop();
    check(is_identity(animator->joint_matrices(0)[1]), "stop() restores the bind pose");
}

} // namespace

int main(int argc, char** argv)
{
    const std::string asset_dir = argc > 1 ? argv[1] : "tests/assets";

    if(!glfwInit())
    {
        std::cerr << "could not initialise glfw\n";
        return 77; // treated as "skipped" by ctest
    }

    glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);

    GLFWwindow* window = glfwCreateWindow(64, 64, "nle gltf test", nullptr, nullptr);
    if(!window)
    {
        std::cerr << "could not create a hidden gl context\n";
        glfwTerminate();
        return 77;
    }

    glfwMakeContextCurrent(window);

    glewExperimental = GL_TRUE;
    if(glewInit() != GLEW_OK)
    {
        std::cerr << "could not initialise glew\n";
        glfwDestroyWindow(window);
        glfwTerminate();
        return 77;
    }

    try
    {
        test_model(asset_dir + "/skinned_bar.gltf");
        test_model(asset_dir + "/skinned_bar.glb");
    }
    catch(const std::exception& e)
    {
        std::cerr << "\nunexpected exception: " << e.what() << "\n";
        ++g_failures;
    }

    glfwDestroyWindow(window);
    glfwTerminate();

    std::cout << "\n" << (g_checks - g_failures) << "/" << g_checks << " checks passed\n";
    return g_failures == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
}
