#!/usr/bin/env python3
"""Regenerate src/nle/static/default_shader.cpp from the files in shader/.

The engine needs the default shaders available without touching the filesystem,
so they are compiled in as string literals. Keeping that copy by hand meant the
two versions drifted; run this after editing shader/default_*.glsl instead.

    python3 tools/embed_shaders.py
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src/nle/static/default_shader.cpp"

SHADERS = [
    ("DEFAULT_VERTEX_SHADER", "shader/default_vert.glsl"),
    ("DEFAULT_FRAGMENT_SHADER", "shader/default_frag.glsl"),
]

DELIMITER = "GLSL"


def main() -> int:
    parts = [
        "// Generated by tools/embed_shaders.py -- do not edit by hand.",
        "// Edit shader/default_vert.glsl and shader/default_frag.glsl, then rerun it.",
        "",
        '#include "default_shader.h"',
        "",
        "namespace nle",
        "{",
        "",
    ]

    for name, relative_path in SHADERS:
        source = (ROOT / relative_path).read_text()

        if f'){DELIMITER}"' in source:
            print(f"error: {relative_path} contains the raw string delimiter", file=sys.stderr)
            return 1

        parts.append(f"    /// contents of {relative_path}")
        parts.append(f"    const char *{name} =")
        parts.append(f'R"{DELIMITER}({source}){DELIMITER}";')
        parts.append("")

    parts.append("} // namespace nle")
    parts.append("")

    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
