// Generated by tools/embed_shaders.py -- do not edit by hand.
// Edit shader/default_vert.glsl and shader/default_frag.glsl, then rerun it.

#include "default_shader.h"

namespace nle
{

    /// contents of shader/default_vert.glsl
    const char *DEFAULT_VERTEX_SHADER =
R"GLSL(#version 330

#define NLE_MAX_JOINTS 64

out vec4 io_vertex_color;
out vec2 io_texture_coordinates;
out vec3 io_normal;
out vec3 io_frag_position;

uniform mat4 u_model;
uniform mat4 u_projection;
uniform mat4 u_view;

// Skinning. u_joint_matrices holds, for the skin this draw belongs to,
// joint_world_matrix * inverse_bind_matrix for every joint.
uniform int u_skinning_enabled;
uniform mat4 u_joint_matrices[NLE_MAX_JOINTS];

layout (location = 0) in vec3 position;
layout (location = 1) in vec3 normal;
layout (location = 2) in vec3 color;
layout (location = 3) in vec2 texture;
layout (location = 4) in vec4 joints;
layout (location = 5) in vec4 weights;

int joint_index(float raw)
{
    // Clamped so malformed weights can never index outside the array.
    return int(clamp(raw, 0.0, float(NLE_MAX_JOINTS - 1)));
}

mat4 skin_matrix()
{
    float total = weights.x + weights.y + weights.z + weights.w;

    if (total <= 0.0)
    {
        return mat4(1.0);
    }

    mat4 skin = weights.x * u_joint_matrices[joint_index(joints.x)]
              + weights.y * u_joint_matrices[joint_index(joints.y)]
              + weights.z * u_joint_matrices[joint_index(joints.z)]
              + weights.w * u_joint_matrices[joint_index(joints.w)];

    return skin / total;
}

void main() {
    mat4 model = u_model;

    if (u_skinning_enabled == 1)
    {
        model = model * skin_matrix();
    }

    vec4 world_position = model * vec4(position, 1.0);

    gl_Position = u_projection * u_view * world_position;
    io_texture_coordinates = texture;
    io_normal = mat3(transpose(inverse(model))) * normal;
    io_frag_position = world_position.xyz;
    io_vertex_color = vec4(color, 1.0f);
}
)GLSL";

    /// contents of shader/default_frag.glsl
    const char *DEFAULT_FRAGMENT_SHADER =
R"GLSL(#version 330

#define NLE_MAX_POINT_LIGHTS 8

in vec4 io_vertex_color;
in vec2 io_texture_coordinates;
in vec3 io_normal;
in vec3 io_frag_position;

out vec4 io_color;

struct DirectionalLight
{
    // Direction *towards* the light, i.e. the light object's front vector.
    vec3 direction;
    vec3 color;
    vec3 ambient;
    vec3 diffuse;
    vec3 specular;
    int enabled;
};

struct PointLight
{
    vec3 position;
    vec3 color;
    vec3 ambient;
    vec3 diffuse;
    vec3 specular;

    // attenuation = 1 / (constant + linear * d + quadratic * d * d)
    float constant;
    float linear;
    float quadratic;

    // hard cutoff; the last quarter of the range is faded out so the cutoff
    // itself is not visible as an edge.
    float range;
};

struct Material
{
    float shininess;
    float dissolve;
    vec3 ambient;
    vec3 diffuse;
    vec3 specular;
    int accept_light;
    float fog_limit;
};

struct Sky
{
    int distance_fog_enabled;
    float distance_fog_near;
    float distance_fog_far;
    vec3 distance_fog_color;
};

uniform int u_lighting_enabled = 1;
uniform int u_point_lighting_enabled = 1;
uniform int u_texture_enabled = 0;
uniform sampler2D u_texture_0;

uniform DirectionalLight u_directional_light;
uniform PointLight u_point_lights[NLE_MAX_POINT_LIGHTS];
uniform int u_point_light_count;

uniform Material u_material;
uniform Sky u_sky;
uniform vec3 u_eye_position;
uniform float u_time;

vec3 directional_light_contribution(vec3 normal, vec3 view_direction)
{
    vec3 direction = normalize(u_directional_light.direction);

    // The light's own ambient term belongs here too; leaving it out made
    // light::set_ambient() a no-op for directional lights. It defaults to
    // white, so default lights are unaffected.
    vec3 ambient = u_directional_light.color * u_directional_light.ambient * u_material.ambient;

    float diffuse_factor = max(dot(normal, direction), 0.0);
    vec3 diffuse = u_material.diffuse * u_directional_light.diffuse * diffuse_factor;

    vec3 reflect_direction = reflect(-direction, normal);
    float specular_factor = pow(max(dot(view_direction, reflect_direction), 0.0), max(u_material.shininess, 1.0));
    vec3 specular = u_material.specular * u_directional_light.specular * specular_factor;

    return ambient + diffuse + specular;
}

vec3 point_light_contribution(PointLight light, vec3 normal, vec3 view_direction)
{
    vec3 to_light = light.position - io_frag_position;
    float dist = length(to_light);

    if (dist > light.range)
    {
        return vec3(0.0);
    }

    vec3 direction = dist > 0.0 ? to_light / dist : normal;

    float attenuation = 1.0 / (light.constant + light.linear * dist + light.quadratic * dist * dist);
    attenuation *= 1.0 - smoothstep(light.range * 0.75, light.range, dist);

    vec3 ambient = light.ambient * u_material.ambient;

    float diffuse_factor = max(dot(normal, direction), 0.0);
    vec3 diffuse = light.diffuse * u_material.diffuse * diffuse_factor;

    vec3 reflect_direction = reflect(-direction, normal);
    float specular_factor = pow(max(dot(view_direction, reflect_direction), 0.0), max(u_material.shininess, 1.0));
    vec3 specular = light.specular * u_material.specular * specular_factor;

    return light.color * (ambient + diffuse + specular) * attenuation;
}

float fog_factor()
{
    float f = (distance(u_eye_position, io_frag_position) - u_sky.distance_fog_near) /
              max(u_sky.distance_fog_far - u_sky.distance_fog_near, 0.0001);
    return clamp(f, 0.0, 1.0);
}

void main() {
    vec3 normal = normalize(io_normal);
    vec3 view_direction = normalize(u_eye_position - io_frag_position);

    vec4 base_color = u_texture_enabled == 1
        ? texture(u_texture_0, io_texture_coordinates)
        : io_vertex_color;

    // Unlit surfaces (the sky, for one) keep their colour untouched.
    vec3 light_factor = vec3(1.0);

    if (u_lighting_enabled == 1 || u_point_lighting_enabled == 1)
    {
        light_factor = vec3(0.0);

        if (u_lighting_enabled == 1)
        {
            light_factor += directional_light_contribution(normal, view_direction);
        }

        if (u_point_lighting_enabled == 1)
        {
            for (int i = 0; i < u_point_light_count && i < NLE_MAX_POINT_LIGHTS; ++i)
            {
                light_factor += point_light_contribution(u_point_lights[i], normal, view_direction);
            }
        }
    }

    io_color = vec4(base_color.rgb * light_factor, base_color.a * u_material.dissolve);

    if (u_sky.distance_fog_enabled == 1)
    {
        io_color.rgb = mix(io_color.rgb, u_sky.distance_fog_color,
                           min(fog_factor(), u_material.fog_limit));
    }
}
)GLSL";

} // namespace nle
